package types
 
// ClientRequest is what a connected client sends over the websocket: a
// prompt paired with an image to run it against. encoding/json base64
// encodes/decodes the []byte field automatically.
type ClientRequest struct {
	Prompt string `json:"prompt"`
	Img    []byte `json:"img"`
}

// Request is what the gateway pushes onto the "requests" stream for a
// separate inference worker to pick up. ImgKey points at where the raw
// image bytes were stored via Database.SetImage.
type Request struct {
	ID     string `json:"id"`
	Prompt string `json:"prompt"`
}

// InferenceResult is the result of inference workers.
type InferenceResult struct {
	// ID shows which client made this request, for easier routing back.
	ID		string `json:"id"`
	
	Prompt  string `json:"prompt"`

	// Img contains the inferenced image, generated by model.
	Img  	[]byte `json:"img"`

	// Result contains the actual result of inference.
	Result	string `json:"result"`
}

// Result is what an inference worker pushes onto the "RESULTS" stream
// once it has processed a Request. ID matches the originating Request's
// ID so the gateway can route it back to the right client.
type Result struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
	Img  	[]byte `json:"img"`
	Inference string `json:"inference"`
	Time    int64  `json:"time"`
	Date    string `json:"date"`
}